Fix handling of packages and 'all' while PWD is inside a category.

diff --git a/libexec/build-make b/libexec/build-make
--- a/libexec/build-make
+++ b/libexec/build-make
@@ -62,16 +62,17 @@ build_make()
 		# discard everything else.
 		case "${package}" in
 		(-*|*/all|all) continue;;
+		(*/*)	CATEGORY="${package%%/*}";;
+		(*)	if [ "${PWD##${BUILDER_PKGDIR}/}" != "${PWD}" ]; then
+				CATEGORY="${category%%/*}"
+			fi;;
 		esac
 
-		CATEGORY="${package%%/*}"
-		if [ "${CATEGORY}" != 'all' ]; then
-			if [ ! -d "${BUILDER_PKGDIR}/${CATEGORY}" ]; then
-				die "invalid package category '${CATEGORY}'"
-			fi
-			if ! build-query --exists "${package}"; then
-				exit 1
-			fi
+		if [ ! -d "${BUILDER_PKGDIR}/${CATEGORY}" ]; then
+			die "invalid package category '${CATEGORY}'"
+		fi
+		if ! build-query --exists "${package}"; then
+			exit 1
 		fi
 	done
 
