Make various sub-commands proper builder libraries
 * Have fixed up various sub-commands so that they can now be used via import()
   as well as executed as a command.

diff --git a/libexec/build-make b/libexec/build-make
--- a/libexec/build-make
+++ b/libexec/build-make
@@ -1,113 +1,113 @@
 #!/usr/bin/env build
 
-while test "$#" -gt '0'; do
-	case "${1}" in
-	(-h|-help|--help) usage; exit 0;;
-	(--)	shift; break;;
-	(-*)	error "unknown optopn '${1}'"
+build_make()
+{
+	if test "$#" -eq '0'; then
+		error 'no make action specified'
 		echo "try 'build help make'" >&2
-		exit 1;;
-	(*)	break;;
-	esac
-done
-
-if test "$#" -eq '0'; then
-	error 'no make action specified'
-	echo "try 'build help make'" >&2
-	exit 1
-fi
-
-BUILDER_MAKE_ACTION="${1}"
-shift
-
-# This allows 'build install --help' to work.
-for arg; do
-	case "${arg}" in
-	(-h|-help|--help) exec build make-"${BUILDER_MAKE_ACTION}" --help;;
-	esac
-done
-
-# If no target is given, then base our target on the current working directory,
-# falling back to "${PROJECT}/all" as our default.
-if test "$#" -eq '0'; then
-	case "${BUILDER_MAKE_ACTION}" in
-	(*clean) NAME='all/all';;
-	(*)	 NAME="${TARGET}";;
-	esac
-
-	# Are we somewhere within the pkg structure.  If this test succeeds
-	# then we are at least in a category directory within the pkgdir.  Just
-	# being in pkgdir is not enough to change our default argument list
-	# handling.
-	if [ "${PWD##${BUILDER_PKGDIR}/}" != "${PWD}" ]; then
-		category="${PWD##${BUILDER_PKGDIR}/}"
-		if [ "${category%%/*}" != "${category}" ]; then
-			name="${category#*/}"
-			category="${category%%/*}"
-			NAME="${category}/${name%%/*}"
-		else
-			NAME="${category}/all"
-		fi
-		unset category
-		unset name
+		exit 1
 	fi
-	set -- "${NAME}"
-fi
 
-# FIXME move this to a sub-command to be used by other tools.
-for package in "$@"; do
-	# If all is specified anywhere in the argument list than just discard
-	# everything else.
-	case "${package}" in
-	(-*|*/all|all) continue;;
-	esac
+	BUILDER_MAKE_ACTION="${1}"
+	shift
 
-	CATEGORY="${package%%/*}"
-	if [ "${CATEGORY}" != 'all' ]; then
-		if [ ! -d "${BUILDER_PKGDIR}/${CATEGORY}" ]; then
-			die "invalid package category '${CATEGORY}'"
+	# This allows 'build <command> --help' to work.
+	for arg; do
+		case "${arg}" in
+		(-h|-help|--help) exec build make-"${BUILDER_MAKE_ACTION}" --help;;
+		esac
+	done
+
+	# If no target is given, then base our target on the current working
+	# directory, falling back to "${PROJECT}/all" as our default.
+	if test "$#" -eq '0'; then
+		case "${BUILDER_MAKE_ACTION}" in
+		(*clean) NAME='all/all';;
+		(*)	 NAME="${TARGET}";;
+		esac
+
+		# Are we somewhere within the pkg structure.  If this test
+		# succeeds then we are at least in a category directory within
+		# the pkgdir.  Just being in pkgdir is not enough to change our
+		# default argument list handling.
+		if [ "${PWD##${BUILDER_PKGDIR}/}" != "${PWD}" ]; then
+			category="${PWD##${BUILDER_PKGDIR}/}"
+			if [ "${category%%/*}" != "${category}" ]; then
+				name="${category#*/}"
+				category="${category%%/*}"
+				NAME="${category}/${name%%/*}"
+			else
+				NAME="${category}/all"
+			fi
+			unset category
+			unset name
 		fi
-		if ! build-query --exists "${package}"; then
-			exit 1
-		fi
+		set -- "${NAME}"
 	fi
-done
 
-# sort/uniq the argument list
-# FIXME need a way to "resolve" the package list instead of possibly clobbering
-# it.
-set -- $(for package in "$@"; do echo "${package}" ; done | sort | uniq)
+	# FIXME move this to a sub-command to be used by other tools.
+	for package in "$@"; do
+		# If all is specified anywhere in the argument list than just
+		# discard everything else.
+		case "${package}" in
+		(-*|*/all|all) continue;;
+		esac
 
-# build the Makefile
-trap cleanup EXIT
-test -d "${BUILDER_TMPDIR}" || mkdir -p "${BUILDER_TMPDIR}"
-BUILDER_MAKEFILE="$(mktemp "${BUILDER_TMPDIR}/builder_makefile.XXXXXXXX")"
-if [ ! -f "${BUILDER_MAKEFILE}" ]; then
-	die "failed to generate build dependencies"
+		CATEGORY="${package%%/*}"
+		if [ "${CATEGORY}" != 'all' ]; then
+			if [ ! -d "${BUILDER_PKGDIR}/${CATEGORY}" ]; then
+				die "invalid package category '${CATEGORY}'"
+			fi
+			if ! build-query --exists "${package}"; then
+				exit 1
+			fi
+		fi
+	done
+
+	# sort/uniq the argument list
+	# FIXME need a way to "resolve" the package list instead of possibly
+	# clobbering it.
+	set -- $(for package in "$@"; do echo "${package}" ; done | sort | uniq)
+
+	# build the Makefile
+	trap cleanup EXIT
+	test -d "${BUILDER_TMPDIR}" || mkdir -p "${BUILDER_TMPDIR}"
+	BUILDER_MAKEFILE="$(mktemp "${BUILDER_TMPDIR}/builder_makefile.XXXXXXXX")"
+	if [ ! -f "${BUILDER_MAKEFILE}" ]; then
+		die "failed to generate build dependencies"
+	fi
+	export BUILDER_MAKEFILE
+	"${BUILDER_LIBDIR}/build-makedeps" || die "failed generate build dependencies"
+
+	packages=
+	for package in "$@"; do
+		case "${package}" in
+		(all|*/all);;
+		(*) package="$(build-query --pkgname "${package}")";;
+		esac
+		package="$(echo "${package}"|tr '/-' '__')"
+		packages="${packages} ${package}_${BUILDER_MAKE_ACTION}"
+	done
+	set -- ${packages}
+	unset packages
+
+	# The 'tee' command will discard the exit status from 'make', so we
+	# have to jump through a few hoops to capture the exit status in a
+	# portable fashion.
+	BUILDER_PIPE="`mktemp "${BUILDER_TMPDIR}/builder_pipe.XXXXXXXX"`"
+	test -f "${BUILDER_PIPE}" || die 'failed to generate log-pipe placeholder'
+	rm -f "${BUILDER_PIPE}" && mkfifo "${BUILDER_PIPE}" || die 'failed to create log-pipe'
+	tee "${BUILDER_TMPDIR}/builder.log" < "${BUILDER_PIPE}" &
+	BUILDER_LOGGER="$!"
+	make -r -f "${BUILDER_MAKEFILE}" "${@}" > "${BUILDER_PIPE}" 2>&1
+	exit $?
+}
+
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'make' '<action> [all|[<category>/]<package|all>]' "$@"
+	build_make "${@}"
 fi
-export BUILDER_MAKEFILE
-"${BUILDER_LIBDIR}/build-makedeps" || die "failed generate build dependencies"
 
-packages=
-for package in "$@"; do
-	case "${package}" in
-	(all|*/all);;
-	(*) package="$(build-query --pkgname "${package}")";;
-	esac
-	package="$(echo "${package}"|tr '/-' '__')"
-	packages="${packages} ${package}_${BUILDER_MAKE_ACTION}"
-done
-set -- ${packages}
-unset packages
 
-# The 'tee' command will discard the exit status from 'make', so we have to
-# jump through a few hoops to capture the exit status in a portable fashion.
-BUILDER_PIPE="`mktemp "${BUILDER_TMPDIR}/builder_pipe.XXXXXXXX"`"
-test -f "${BUILDER_PIPE}" || die 'failed to generate log-pipe placeholder'
-rm -f "${BUILDER_PIPE}" && mkfifo "${BUILDER_PIPE}" || die 'failed to create log-pipe'
-tee "${BUILDER_TMPDIR}/builder.log" < "${BUILDER_PIPE}" &
-BUILDER_LOGGER="$!"
-make -r -f "${BUILDER_MAKEFILE}" "${@}" > "${BUILDER_PIPE}" 2>&1
-exit $?
 
 # vim: filetype=sh
diff --git a/libexec/build-make-compile b/libexec/build-make-compile
--- a/libexec/build-make-compile
+++ b/libexec/build-make-compile
@@ -28,68 +28,75 @@ build_compile()
 }
 pkg_compile() { build_compile; }
 
-load_rules "${1}"
+build_make_compile()
+{
+	load_rules "${1}"
 
-# Declare compilation variables before loading the rules as the package may
-# potentially overwrite this data, in particular the toolchain data is usually
-# rewritten within the toolchain/buildtools rule.
-echo "compiling: ${1}"
-eval "$(build-query --toolchain "${CHOST}")"
-mkenv "compile"
-PKG_LOGFILE="${L}/compile.log"
+	# Declare compilation variables before loading the rules as the package
+	# may potentially overwrite this data, in particular the toolchain data
+	# is usually rewritten within the toolchain/buildtools rule.
+	echo "compiling: ${1}"
+	eval "$(build-query --toolchain "${CHOST}")"
+	mkenv "compile"
+	PKG_LOGFILE="${L}/compile.log"
 
-# pkgconfig can be a right pita...
-PKG_CONFIG_LIBDIR="${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/pkgconfig"
-PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
-export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH
-export PKG_CONFIG_SYSROOT_DIR
+	# pkgconfig can be a right pita...
+	PKG_CONFIG_LIBDIR="${SYSROOT}/usr/share/pkgconfig:${SYSROOT}/usr/lib/pkgconfig"
+	PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
+	export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH
+	export PKG_CONFIG_SYSROOT_DIR
 
-# Don't pass along the builder jobcontrol data to child processes
-unset MAKEFLAGS
+	# Don't pass along the builder jobcontrol data to child processes
+	unset MAKEFLAGS
 
-load_rules "${1}"
+	load_rules "${1}"
 
-## Prep the build environment
-# Technically much of this should have been done in build-prep, and this sort
-# of duplication of work may be useful to make a function within the top-level
-# build script.  Perhaps builder_mkenv [prep|compile|archive|etc..]
+	## Build the source and install it into the DESTDIR
+	# Ironically this is the heart of what the build-engine does, and yet it has
+	# been reduced to the simplest component of the entire system.
+	cd "${S}"
+	pkg_compile >> "${PKG_LOGFILE}" 2>&1
 
-## Build the source and install it into the DESTDIR
-# Ironically this is the heart of what the build-engine does, and yet it has
-# been reduced to the simplest component of the entire system.
-cd "${S}"
-pkg_compile >> "${PKG_LOGFILE}" 2>&1
+	## Save Space!
+	# At this point everything important should be installed into ${D}, and
+	# any form of reruning the build will remove ${S} before prepping it
+	# for build, so we might as well gut it now.  About the best option we
+	# could do would be to avoid gutting this when being run in --debug
+	# mode.
+	find "${S}" -delete &
 
-## Save Space!
-# At this point everything important should be installed into ${D}, and any
-# form of reruning the build will remove ${S} before prepping it for build, so
-# we might as well gut it now.  About the best option we could do would be to
-# avoid gutting this when being run in --debug mode.
-find "${S}" -delete &
-
-##
-# Generate the file index.  This is done as a 0 delimited file stored within
-# the destination filesystem.  This allows for easy checking of the installed
-# data as well as easy removal of individual binary packages from the sysroot.
-mkdir -p "${D}/var/db/binpkgs/${CATEGORY}"
-binpkg_list="$(mktemp "${T}/binpkg.XXXXXXXX")"
-if [ ! -e "${binpkg_list}" ]; then
-	die "failed to create package inventory"
-fi
-cd "${D}"
-for dir in man usr/man usr/share/man; do
-	test -d "${dir}" || continue
-	for file in `find "${dir}" -regex '.*[1-9]$'`; do
-		if test -f "${file}"; then
-			gzip -c -9 "${file}" > "${file}.gz" && rm "${file}"
-		elif test -h "${file}"; then
-			mv "${file}" "${file}.gz"
-		fi
+	##
+	# Generate the file index.  This is done as a 0 delimited file stored
+	# within the destination filesystem.  This allows for easy checking of
+	# the installed data as well as easy removal of individual binary
+	# packages from the sysroot.
+	mkdir -p "${D}/var/db/binpkgs/${CATEGORY}"
+	binpkg_list="$(mktemp "${T}/binpkg.XXXXXXXX")"
+	if [ ! -e "${binpkg_list}" ]; then
+		die "failed to create package inventory"
+	fi
+	cd "${D}"
+	for dir in man usr/man usr/share/man; do
+		test -d "${dir}" || continue
+		for file in `find "${dir}" -regex '.*[1-9]$'`; do
+			if test -f "${file}"; then
+				gzip -c -9 "${file}" > "${file}.gz" && rm "${file}"
+			elif test -h "${file}"; then
+				mv "${file}" "${file}.gz"
+			fi
+		done
+		wait
 	done
 	wait
-done
-wait
-find * -depth \( ! -type d \) -print0 > "${binpkg_list}"
-mv "${binpkg_list}" "${D}/var/db/binpkgs/${CATEGORY}/${NAME}"
+	find * -depth \( ! -type d \) -print0 > "${binpkg_list}"
+	mv "${binpkg_list}" "${D}/var/db/binpkgs/${CATEGORY}/${NAME}"
+}
+
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'compile' '[all|[<category>/]<package|all>]' "$@"
+	build_make_compile "${@}"
+fi
+
+
 
 # vim: filetype=sh
diff --git a/libexec/build-make-export b/libexec/build-make-export
--- a/libexec/build-make-export
+++ b/libexec/build-make-export
@@ -1,94 +1,103 @@
 #!/usr/bin/env build
 
-load_rules "${1}"
+build_make_export()
+{
+	load_rules "${1}"
 
-if test -z "${LICENSE}"; then
-	die "no license set in '${1}'"
-fi
-
-echo "exporting ${1}"
-
-for dir in "${S}" "${D}"; do
-	if ! test -d "${dir}"; then
-		continue
+	if test -z "${LICENSE}"; then
+		die "no license set in '${1}'"
 	fi
-	mv "${dir}" "${dir}.old"
-	find "${dir}.old" -delete &
-done
-unset dir
 
-mkenv 'export'
-EXPORT_LOGFILE="${L}/export.log"
+	echo "exporting ${1}"
 
-mkdir -p "${T}/${NAME}-${VERSION}.builder"
-cp "${RULESFILE}" "${T}/${NAME}-${VERSION}.builder/"
-
-if ! test -z "${PATCHES}"; then
-	for patch in ${PATCHES}; do
-		cp "${F}/${NAME}-${VERSION}-${patch}.patch" "${T}/${NAME}-${VERSION}.builder/"
+	for dir in "${S}" "${D}"; do
+		if ! test -d "${dir}"; then
+			continue
+		fi
+		mv "${dir}" "${dir}.old"
+		find "${dir}.old" -delete &
 	done
-fi
+	unset dir
 
-cd "${T}"
+	mkenv 'export'
+	EXPORT_LOGFILE="${L}/export.log"
 
-for url in ${SOURCE_URI}; do
-	file="$(build-url --archive "${url}")"
-	test -f "${BUILDER_SRCDIR}/${file}" || die "source does not exist '${file}'"
-	cp "${BUILDER_SRCDIR}/${file}" "${NAME}-${VERSION}.builder/"
-done
+	mkdir -p "${T}/${NAME}-${VERSION}.builder"
+	cp "${RULESFILE}" "${T}/${NAME}-${VERSION}.builder/"
 
-for dir in SOURCES SPECS RPMS BUILD; do
-	mkdir -p "${S}/${dir}" &
-done
-wait
+	if ! test -z "${PATCHES}"; then
+		for patch in ${PATCHES}; do
+			cp "${F}/${NAME}-${VERSION}-${patch}.patch" "${T}/${NAME}-${VERSION}.builder/"
+		done
+	fi
 
-if ! tar czf "${S}/SOURCES/${NAME}-${VERSION}.builder.tar.gz" "${NAME}-${VERSION}.builder"; then
-	die "Failed to create base rpm tarball."
-fi
+	cd "${T}"
 
-cat <<EOF > "${S}/SPECS/${NAME}-${VERSION}.spec"
-Summary: ${DESCRIPTION}
-Name: ${NAME}
-Version: ${VERSION}
-Release: ${RELEASE}
-License: ${LICENSE}
-Group: ${CATEGORY}
-Source: ${NAME}-${VERSION}.builder.tar.gz
-Buildroot: ${SYSROOT}
-%description
-${DESCRIPTION}
+	for url in ${SOURCE_URI}; do
+		file="$(build-url --archive "${url}")"
+		test -f "${BUILDER_SRCDIR}/${file}" || die "source does not exist '${file}'"
+		cp "${BUILDER_SRCDIR}/${file}" "${NAME}-${VERSION}.builder/"
+	done
 
-%prep
-%setup -c
+	for dir in SOURCES SPECS RPMS BUILD; do
+		mkdir -p "${S}/${dir}" &
+	done
+	wait
 
-%build
+	if ! tar czf "${S}/SOURCES/${NAME}-${VERSION}.builder.tar.gz" "${NAME}-${VERSION}.builder"; then
+		die "Failed to create base rpm tarball."
+	fi
 
-%install
+	cat <<-EOF > "${S}/SPECS/${NAME}-${VERSION}.spec"
+	Summary: ${DESCRIPTION}
+	Name: ${NAME}
+	Version: ${VERSION}
+	Release: ${RELEASE}
+	License: ${LICENSE}
+	Group: ${CATEGORY}
+	Source: ${NAME}-${VERSION}.builder.tar.gz
+	Buildroot: ${SYSROOT}
+	%description
+	${DESCRIPTION}
 
-%clean
+	%prep
+	%setup -c
 
-%files
-EOF
-# FIXME In the long run we should see about producing -dbg and -dev rpms
-tr '\000' '\n' < "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}" \
-	| sed -e 's,^,/,' \
-	| grep -v '^/usr/include' | grep -v 'pkgconfig' | grep -v '^*\.a$' \
-	>> "${S}/SPECS/${NAME}-${VERSION}.spec"
+	%build
 
-#mkdir -p "${D}"
-#cd "${D}"
-#tar xaf "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}"
+	%install
 
-rpmbuild --quiet --target "${CHOST}"	\
-	--define "_topdir ${S}"		\
-	--define "buildroot ${SYSROOT}"	\
-	--define '_unpackaged_files_terminate_build 0'	\
-	--define '_missing_doc_files_terminate_build 0'	\
-	--define "arch ${CHOST%%-*}"	\
-	-bb "${S}/SPECS/${NAME}-${VERSION}.spec" > "${L}/export.log" 2>&1 || die "Failed to integrate rpm spec file"
+	%clean
 
-mkdir -p "${BUILDER_TOPDIR}/exports"
+	%files
+	EOF
+
+	# FIXME In the long run we should see about producing -dbg and -dev rpms
+	tr '\000' '\n' < "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}" \
+		| sed -e 's,^,/,' \
+		| grep -v '^/usr/include' | grep -v 'pkgconfig' | grep -v '^*\.a$' \
+		>> "${S}/SPECS/${NAME}-${VERSION}.spec"
+
+	#mkdir -p "${D}"
+	#cd "${D}"
+	#tar xaf "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}"
+
+	rpmbuild --quiet --target "${CHOST}"	\
+		--define "_topdir ${S}"		\
+		--define "buildroot ${SYSROOT}"	\
+		--define '_unpackaged_files_terminate_build 0'	\
+		--define '_missing_doc_files_terminate_build 0'	\
+		--define "arch ${CHOST%%-*}"	\
+		-bb "${S}/SPECS/${NAME}-${VERSION}.spec" > "${L}/export.log" 2>&1 || die "Failed to integrate rpm spec file"
+
+	mkdir -p "${BUILDER_TOPDIR}/exports"
 # FIXME figure out the arch properly
-mv "${S}/RPMS/${CHOST%%-*}/${NAME}-${VERSION}-${RELEASE}.${CHOST%%-*}.rpm" "${BUILDER_TOPDIR}/exports/" || die "Failed to move rpm"
+	mv "${S}/RPMS/${CHOST%%-*}/${NAME}-${VERSION}-${RELEASE}.${CHOST%%-*}.rpm" "${BUILDER_TOPDIR}/exports/" || die "Failed to move rpm"
+}
+
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'export' '[all|[<category>/]<package|all>]' "$@"
+	build_make_export "${@}"
+fi
 
 # vim: filetype=sh
diff --git a/libexec/build-make-install b/libexec/build-make-install
--- a/libexec/build-make-install
+++ b/libexec/build-make-install
@@ -1,53 +1,41 @@
 #!/usr/bin/env build
 
-usage()
+build_make_install()
 {
-cat<<END_OF_USAGE
-END_OF_USAGE
+	echo "installing: ${1}"
+	eval $(build-query --environ "${1}")
+
+	if [ ! -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" ]; then
+		die "archive does not exist for package '${NAME}'"
+	fi
+	if [ ! -d "${SYSROOT}" ]; then
+		mkdir -p "${SYSROOT}" || die "failed to create system root @ '${SYSROOT}'"
+	fi
+
+	# FIXME the builder configs should decide the binpkg archive format.
+	case "${ARCHIVE_FORMAT}" in
+	(tbz2|tar.bz2)	ARCHIVE_DECOMPRESSOR="bzip2 -dc";;
+	(tgz|tar.gz)	ARCHIVE_DECOMPRESSOR="gzip -dc";;
+	(*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
+	esac
+
+	cd "${SYSROOT}"
+
+	if [ -f "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}" ]; then
+		echo "${NAME}: removing previous version"
+		cat "var/db/binpkgs/${CATEGORY}/${NAME}" | xargs -0 rm  -f
+		rm "var/db/binpkgs/${CATEGORY}/${NAME}"
+	fi
+
+	${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" | tar x
+	touch "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}"
 }
 
-for arg; do
-	case "${arg}" in
-	(-h|-help|--help) usage; exit 0;;
-	esac
-done
-
-while test "$#" -gt '0'; do
-	case "$1" in
-	(-*)	error "unknown argument '${1}'"
-		echo "try 'build help install'" >&2
-		exit 1;;
-	(--)	shift; break;;
-	(*)	break;;
-	esac
-done
-
-echo "installing: ${1}"
-eval $(build-query --environ "${1}")
-
-if [ ! -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" ]; then
-	die "archive does not exist for package '${NAME}'"
-fi
-if [ ! -d "${SYSROOT}" ]; then
-	mkdir -p "${SYSROOT}" || die "failed to create system root @ '${SYSROOT}'"
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'install' '[all|[<category>/]<package|all>]' "$@"
+	build_make_install "${@}"
 fi
 
-# FIXME the builder configs should decide the binpkg archive format.
-case "${ARCHIVE_FORMAT}" in
-(tbz2|tar.bz2)	ARCHIVE_DECOMPRESSOR="bzip2 -dc";;
-(tgz|tar.gz)	ARCHIVE_DECOMPRESSOR="gzip -dc";;
-(*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
-esac
 
-cd "${SYSROOT}"
-
-if [ -f "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}" ]; then
-	echo "${NAME}: removing previous version"
-	cat "var/db/binpkgs/${CATEGORY}/${NAME}" | xargs -0 rm  -f
-	rm "var/db/binpkgs/${CATEGORY}/${NAME}"
-fi
-
-${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" | tar x
-touch "${SYSROOT}/var/db/binpkgs/${CATEGORY}/${NAME}"
 
 # vim: filetype=sh
diff --git a/libexec/build-make-package b/libexec/build-make-package
--- a/libexec/build-make-package
+++ b/libexec/build-make-package
@@ -1,8 +1,8 @@
 #!/usr/bin/env build
 
-ARCHIVE_TMP1=
-ARCHIVE_TMP2=
-exit_cleanup()
+BUILD_MAKE_ARCHIVE_TMP1=
+BUILD_MAKE_ARCHIVE_TMP2=
+build_make_archive_cleanup()
 {
 	ret=$?
 
@@ -11,51 +11,62 @@ exit_cleanup()
 		echo "logfile: '${PKG_LOGFILE}'" >&2
 		exit ${ret}
 	fi
-	if [ -f "${ARCHIVE_TMP1}" ]; then
-		rm -f "${ARCHIVE_TMP1}"
+	if [ -f "${BUILD_MAKE_ARCHIVE_TMP1}" ]; then
+		rm -f "${BUILD_MAKE_ARCHIVE_TMP1}"
 	fi
-	if [ -f "${ARCHIVE_TMP2}" ]; then
-		rm -f "${ARCHIVE_TMP2}"
+	if [ -f "${BUILD_MAKE_ARCHIVE_TMP2}" ]; then
+		rm -f "${BUILD_MAKE_ARCHIVE_TMP2}"
 	fi
 	exit 0
 }
-trap exit_cleanup EXIT
 
-echo "archiving: ${1}"
-load_rules "${1}"
-mkenv "archive"
-PKG_LOGFILE="${L}/archive.log"
+build_make_archive()
+{
+	trap build_make_archive_cleanup EXIT
 
-ARCHIVE_TMP1="$(mktemp "${BUILDER_TMPDIR}/${NAME}-${VERSION}-${RELEASE}.XXXXXXXX")"
-ARCHIVE_TMP2="$(mktemp "${BUILDER_TMPDIR}/${NAME}-${VERSION}-${RELEASE}.XXXXXXXX")"
+	echo "archiving: ${1}"
+	load_rules "${1}"
+	mkenv "archive"
+	PKG_LOGFILE="${L}/archive.log"
 
-[ -f "${ARCHIVE_TMP1}" ] || die "failed to create temporary archive for package '${NAME}'"
-[ -f "${ARCHIVE_TMP2}" ] || die "failed to create temporary archive for package '${NAME}'"
+	BUILD_MAKE_ARCHIVE_TMP1="$(mktemp "${BUILDER_TMPDIR}/${NAME}-${VERSION}-${RELEASE}.XXXXXXXX")"
+	[ -f "${BUILD_MAKE_ARCHIVE_TMP1}" ] || die "failed to create temporary archive for package '${NAME}'"
 
-case "${ARCHIVE_FORMAT}" in
-(tbz2|tar.bz2)	ARCHIVE_COMPRESSOR="bzip2 -cv";;
-(tgz|tar.gz)	ARCHIVE_COMPRESSOR="gzip -cv";;
-(*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
-esac
+	BUILD_MAKE_ARCHIVE_TMP2="$(mktemp "${BUILDER_TMPDIR}/${NAME}-${VERSION}-${RELEASE}.XXXXXXXX")"
+	[ -f "${BUILD_MAKE_ARCHIVE_TMP2}" ] || die "failed to create temporary archive for package '${NAME}'"
 
-if [ ! -d "${BUILDER_ATFDIR}/${CATEGORY}" ]; then
-	mkdir -p "${BUILDER_ATFDIR}/${CATEGORY}"
+	case "${ARCHIVE_FORMAT}" in
+	(tbz2|tar.bz2)	ARCHIVE_COMPRESSOR="bzip2 -cv";;
+	(tgz|tar.gz)	ARCHIVE_COMPRESSOR="gzip -cv";;
+	(*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
+	esac
+
+	if [ ! -d "${BUILDER_ATFDIR}/${CATEGORY}" ]; then
+		mkdir -p "${BUILDER_ATFDIR}/${CATEGORY}"
+	fi
+
+	cd "${D}"
+	tar -cvf "${BUILD_MAKE_ARCHIVE_TMP1}" .  > "${PKG_LOGFILE}" 2>&1
+	${ARCHIVE_COMPRESSOR} "${BUILD_MAKE_ARCHIVE_TMP1}" > "${BUILD_MAKE_ARCHIVE_TMP2}" 2>> "${PKG_LOGFILE}"
+	if [ -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" ]; then
+		rm -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}"
+	fi
+	mv -v "${BUILD_MAKE_ARCHIVE_TMP2}" "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" >> "${PKG_LOGFILE}" 2>&1
+	cd "${W}"
+	find "${D}" -delete &
+
+	##
+	# Technically everything should be done but we did throw a number of
+	# things into the background during execution, so go ahead and wait to
+	# see if anything
+	# is stil going.
+	wait
+}
+
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'package' '[all|[<category>/]<package|all>]' "$@"
+	build_make_archive "${@}"
 fi
 
-cd "${D}"
-tar -cvf "${ARCHIVE_TMP1}" .  > "${PKG_LOGFILE}" 2>&1
-${ARCHIVE_COMPRESSOR} "${ARCHIVE_TMP1}" > "${ARCHIVE_TMP2}" 2>> "${PKG_LOGFILE}"
-if [ -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" ]; then
-	rm -f "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}"
-fi
-mv -v "${ARCHIVE_TMP2}" "${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}-${RELEASE}.${ARCHIVE_FORMAT}" >> "${PKG_LOGFILE}" 2>&1
-cd "${W}"
-find "${D}" -delete &
-
-##
-# Technically everything should be done but we did throw a number of things
-# into the background during execution, so go ahead and wait to see if anything
-# is stil going.
-wait
 
 # vim: filetype=sh
diff --git a/libexec/build-make-prep b/libexec/build-make-prep
--- a/libexec/build-make-prep
+++ b/libexec/build-make-prep
@@ -1,8 +1,6 @@
 #!/usr/bin/env build
 
-ARCHIVE_TMP1=
-ARCHIVE_TMP2=
-exit_cleanup()
+build_make_prep_cleanup()
 {
 	ret=$?
 
@@ -11,85 +9,88 @@ exit_cleanup()
 		echo "logfile: '${PKG_LOGFILE}'" >&2
 		exit ${ret}
 	fi
-	if [ -f "${ARCHIVE_TMP1}" ]; then
-		rm -f "${ARCHIVE_TMP1}"
-	fi
-	if [ -f "${ARCHIVE_TMP2}" ]; then
-		rm -f "${ARCHIVE_TMP2}"
-	fi
 	exit 0
 }
-trap exit_cleanup EXIT
 
-build_prep() { return; }
-pkg_prep() { build_prep; }
+build_make_prep()
+{
+	trap build_prep_cleanup EXIT
 
-load_rules "${1}"
+	build_prep() { return; }
+	pkg_prep() { build_prep; }
 
-## Cleanup the build build environment
-for dir in "${S}" "${D}"; do
-	if [ ! -d "${dir}" ]; then
-		continue
-	fi
-	mv "${dir}" "${dir}.old"
-	find "${dir}.old" -delete &
-done
-unset dir
+	load_rules "${1}"
 
-mkenv "prep"
-PKG_LOGFILE="${L}/prep.log"
-
-SOURCE_DIR="${BUILDER_PKGDIR}/${CATEGORY}/${NAME}/source"
-if [ -d "${SOURCE_DIR}" -o -L "${SOURCE_DIR}" ]; then
-	echo "prepping ${1} from source: '${SOURCE_DIR}"
-	if [ "$(command -v rsync)" ]; then
-		if ! rsync -rav --delete "${SOURCE_DIR}/" "${S}"; then
-			die "failed to sync source to '${S}'"
+	# Cleanup the build build environment
+	for dir in "${S}" "${D}"; do
+		if [ ! -d "${dir}" ]; then
+			continue
 		fi
-	else
-		if ! cp -vadpR "${SOURCE_DIR}" "${S}"; then
-			die "failed to copy source to '${S}'"
-		fi
-	fi >> "${PKG_LOGFILE}" 2>&1
-else
-	# FIXME this stuff needs a lot of work
-	for url in ${SOURCE_URI}; do
-		file="$(build-url --archive "${url}")"
-		if [ ! -f "${BUILDER_SRCDIR}/${file}" ]; then
-			die "source does not exist '${file}'"
-		fi
-		echo "prepping ${1} from source: '${BUILDER_SRCDIR}/${file}"
-
-		case "${file}" in
-		(*.tar.Z|*.tar.z|*.tz)
-			tar xZf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.tar.gz|*.tgz)
-			tar xzf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.tar.bz2|*.tbz2)
-			tar xjf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.tar.xz|*.txz)
-			tar xJf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.tar.*)
-			tar xaf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.zip)
-			unzip "${BUILDER_SRCDIR}/${file}" -d "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		(*.jar)
-			cp "${BUILDER_SRCDIR}/${file}" "${W}" >> "${PKG_LOGFILE}" 2>&1;;
-		esac
+		mv "${dir}" "${dir}.old"
+		find "${dir}.old" -delete &
 	done
-fi
+	unset dir
 
-cd "${W}"
-pkg_prep >> "${PKG_LOGFILE}" 2>&1
+	mkenv "prep"
+	PKG_LOGFILE="${L}/prep.log"
 
-# FIXME wrap up the patch command with something more functional
-if [ ! -z "${PATCHES}" ]; then
-	for patch in ${PATCHES}; do
-		echo "${NAME}: applying patch '${patch}'" | tee -a "${PKG_LOGFILE}"
-		if ! patch -l -t -d "${S}" -p1 < "${F}/${NAME}-${VERSION}-${patch}.patch"; then
-			exit 1
+	SOURCE_DIR="${BUILDER_PKGDIR}/${CATEGORY}/${NAME}/source"
+	if [ -d "${SOURCE_DIR}" -o -L "${SOURCE_DIR}" ]; then
+		echo "prepping ${1} from source: '${SOURCE_DIR}"
+		if [ "$(command -v rsync)" ]; then
+			if ! rsync -rav --delete "${SOURCE_DIR}/" "${S}"; then
+				die "failed to sync source to '${S}'"
+			fi
+		else
+			if ! cp -vadpR "${SOURCE_DIR}" "${S}"; then
+				die "failed to copy source to '${S}'"
+			fi
 		fi >> "${PKG_LOGFILE}" 2>&1
-	done
+	else
+		# FIXME this stuff needs a lot of work
+		for url in ${SOURCE_URI}; do
+			file="$(build-url --archive "${url}")"
+			if [ ! -f "${BUILDER_SRCDIR}/${file}" ]; then
+				die "source does not exist '${file}'"
+			fi
+			echo "prepping ${1} from source: '${BUILDER_SRCDIR}/${file}"
+
+			case "${file}" in
+			(*.tar.Z|*.tar.z|*.tz)
+				tar xZf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.tar.gz|*.tgz)
+				tar xzf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.tar.bz2|*.tbz2)
+				tar xjf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.tar.xz|*.txz)
+				tar xJf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.tar.*)
+				tar xaf "${BUILDER_SRCDIR}/${file}" -C "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.zip)
+				unzip "${BUILDER_SRCDIR}/${file}" -d "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			(*.jar)
+				cp "${BUILDER_SRCDIR}/${file}" "${W}" >> "${PKG_LOGFILE}" 2>&1;;
+			esac
+		done
+	fi
+
+	cd "${W}"
+	pkg_prep >> "${PKG_LOGFILE}" 2>&1
+
+	# FIXME wrap up the patch command with something more functional
+	if [ ! -z "${PATCHES}" ]; then
+		for patch in ${PATCHES}; do
+			echo "${NAME}: applying patch '${patch}'" | tee -a "${PKG_LOGFILE}"
+			if ! patch -l -t -d "${S}" -p1 < "${F}/${NAME}-${VERSION}-${patch}.patch"; then
+				exit 1
+			fi >> "${PKG_LOGFILE}" 2>&1
+		done
+	fi
+}
+
+if test "${BUILDER_CALL_STACK}" = '__main__'; then
+	simple_usage 'prep' '[all|[<category>/]<package|all>]' "$@"
+	build_make_prep "${@}"
 fi
 
 # vim: filetype=sh
