build-fetch: enable Subversion svn:// support

diff --git a/builder/build-fetch b/builder/build-fetch
--- a/builder/build-fetch
+++ b/builder/build-fetch
@@ -149,6 +149,47 @@ build_fetch_git()
 	unset build_fetch_git_tag
 }
 
+build_fetch_svn()
+{
+	build_fetch_svn_uri="$(build_fetch_uri "${1}")"
+	build_fetch_svn_uri="${build_fetch_svn_uri%%\?*}"
+	for arg in $(build_fetch_args "${1}"); do
+		case "${arg}" in
+		(archive=*) build_fetch_svn_var="${arg##*=}";;
+		esac
+	done
+	if test -z "${build_fetch_svn_var}"; then
+		die "do not know how to store source from '${1}'"
+	fi
+
+	build_fetch_svn_dir="${build_fetch_svn_var%%.t*}"
+	build_fetch_svn_tmp="$(mktemp -d "${BUILDER_TMPDIR}/${build_fetch_svn_dir}.XXXXXX")"
+	cd "${build_fetch_svn_tmp}"
+	BUILD_FETCH_CLEAN="${BUILD_FETCH_CLEAN} ${build_fetch_svn_tmp}"
+
+	if ! svn checkout "${build_fetch_svn_uri}" "${build_fetch_svn_dir}"; then
+		die "failed to checkout svn source at '${build_fetch_svn_uri}'"
+	fi
+
+	cd "${build_fetch_svn_tmp}"
+	tar caf "${build_fetch_svn_var}" "${build_fetch_svn_dir}"
+
+	if test ! -d "${BUILDER_SRCDIR}"; then
+		mkdir -p "${BUILDER_SRCDIR}"
+	fi
+
+	mv "${build_fetch_svn_var}" "${BUILDER_SRCDIR}/${build_fetch_svn_var}"
+
+	if [ -d "${build_fetch_svn_tmp}" ]; then
+		rm -rf "${build_fetch_svn_tmp}"
+	fi
+
+	unset build_fetch_svn_tmp
+	unset build_fetch_svn_var
+	unset build_fetch_svn_dir
+	unset build_fetch_svn_uri
+}
+
 build_fetch_http()
 {
 	build_fetch_http_file="$(build_fetch_name "${1}")"
@@ -206,6 +247,7 @@ build_fetch()
 	# FIXME this stuff needs a lot of work
 	case "${1}" in
 	(git://*)	build_fetch_git "${1}" > "${FETCH_LOG}";;
+	(svn://*)	build_fetch_svn "${1}" > "${FETCH_LOG}";;
 	(http://*)	build_fetch_http "${1}" > "${FETCH_LOG}";;
 	(https://*)	build_fetch_http "${1}" > "${FETCH_LOG}";;
 	(ftp://*)	build_fetch_http "${1}" > "${FETCH_LOG}";;
