Support toolchain path
* Properly split out installation based on packages being part of the
  toolchain or not.

diff --git a/scripts/builder/build-install b/scripts/builder/build-install
--- a/scripts/builder/build-install
+++ b/scripts/builder/build-install
@@ -3,14 +3,13 @@
 echo "installing: ${1}"
 eval $(build query --environ "${1}")
 
-# FIXME this should be taken care of by the build config
-if [ -z "${ARCHIVE_FORMAT}" ]; then
-	ARCHIVE_FORMAT="tar.bz2"
-fi
-
 [ -f "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" ] || die "archive does not exist for package '${NAME}'"
 if [ ! -d "${SYSROOT}" ]; then
 	mkdir -p "${SYSROOT}" || die "failed to create system root @ '${SYSROOT}'"
+fi
+
+if [ ! -d "${TOOLDIR}" ]; then
+	mkdir -p "${TOOLDIR}" || die "failed to create tools root @ '${TOOLDIR}'"
 fi
 
 # FIXME the builder configs should decide the binpkg archive format.
@@ -20,7 +19,13 @@ case "${ARCHIVE_FORMAT}" in
 (*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
 esac
 
-cd "${SYSROOT}" && ${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" | tar x
+if [ "${CATEGORY}" = "buildtools" ]; then
+	cd "${TOOLDIR}"
+else
+	cd "${SYSROOT}"
+fi
+
+${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" | tar x
 cp -a "${W}/.compiled" "${W}/.installed"
 
 # vim: filetype=sh
