Revert build-archive functionality
* Instead of merging prep/compile/archive into 1 command I have reversed
  direction slightly.  The individual stages/commands will be maintained
  as separate scripts, but they will no longer create time-stamp files so
  that they always get executed every time.

diff --git a/scripts/builder/build-makedeps b/scripts/builder/build-makedeps
--- a/scripts/builder/build-makedeps
+++ b/scripts/builder/build-makedeps
@@ -4,10 +4,11 @@ cat >"${BUILDER_MAKEFILE}" <<EOF
 # Some generic catchall rules
 all: packages_archive
 all_fetch: packages_fetch
-all_prep: packages_prep
 all_clean: tmpdir_clean sysroot_clean
 all_distclean: tmpdir_clean sysroot_clean artifacts_clean tooldir_clean
+all_prep: packages_prep
 all_compile: packages_compile
+all_archive: packages_archive
 all_install: packages_install
 all_makedeps:
 
@@ -24,11 +25,11 @@ artifacts_clean:
 EOF
 
 PACKAGES=
-PACKAGES_PREP=
 PACKAGES_SOURCES=
-PACKAGES_CLEAN=
 PACKAGES_COMPILE=
+PACKAGES_ARCHIVE=
 PACKAGES_INSTALL=
+PACKAGES_CLEAN=
 for package in $(cd "${BUILDER_PKGDIR}" && echo */*); do
 	if ! eval $(build query --environ "${package}"); then
 		die "in package '${package}'"
@@ -37,7 +38,6 @@ for package in $(cd "${BUILDER_PKGDIR}" && echo */*); do
 	package_make="$(echo "${package}"|tr '/-' '__')"
 	package_archive="${BUILDER_ATFDIR}/${CATEGORY}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}"
 	package_install="${W}/.installed"
-	package_prep="${W}/.prepped"
 	package_logdir="${L}"
 
 	package_sources="${RULESFILE}"
@@ -92,26 +92,33 @@ cat <<EOF
 ##
 # ${CATEGORY}/${NAME} - ${DESCRIPTION}
 ${package_make}: ${package_archive}
-${package_make}_install: ${package_install}
-${package_make}_compile: ${package_archive}
 ${package_make}_fetch: ${package_sources}
-${package_make}_makedeps:
-${package_make}_clean:
-	@build-clean ${CATEGORY}/${NAME}
-${package_install}: ${package_archive}
-	@build-install ${CATEGORY}/${NAME}
-${package_archive}: ${package_prep}${package_deps}
-	@if ! build-compile ${CATEGORY}/${NAME}; then \
-		echo "error: failed to compile package '${CATEGORY}/${NAME}'" >&2 ;\
-		echo "logfile: '${L}/compile.log'" >&2 ;\
-		exit 1 ;\
-	fi
+${package_make}_prep: ${package_sources}
 ${package_prep}: ${package_sources}
 	@if ! build-prep ${CATEGORY}/${NAME}; then \
 		echo "error: failed to prepare package '${CATEGORY}/${NAME}'" >&2 ;\
 		echo "logfile: '${L}/prep.log'" >&2 ;\
 		exit 1 ;\
 	fi
+${package_make}_compile: ${package_make}_prep ${package_deps}
+	@if ! build-compile ${CATEGORY}/${NAME}; then \
+		echo "error: failed to compile package '${CATEGORY}/${NAME}'" >&2 ;\
+		echo "logfile: '${L}/compile.log'" >&2 ;\
+		exit 1 ;\
+	fi
+${package_make}_archive: ${package_archive}
+${package_archive}: ${package_make}_compile
+	@if ! build-archive ${CATEGORY}/${NAME}; then \
+		echo "error: failed to archive package '${CATEGORY}/${NAME}'" >&2 ;\
+		echo "logfile: '${L}/archive.log'" >&2 ;\
+		exit 1 ;\
+	fi
+${package_make}_install: ${package_install}
+${package_install}: ${package_archive}
+	@build-install ${CATEGORY}/${NAME}
+${package_make}_makedeps:
+${package_make}_clean:
+	@build-clean ${CATEGORY}/${NAME}
 EOF
 
 	##
@@ -147,8 +154,8 @@ EOF
 	if [ "${CATEGORY}" = "${PROJECT_NAME}" ]; then
 		PACKAGES="${PACKAGES} ${package_make}"
 		PACKAGES_SOURCES="${PACKAGES_SOURCES} ${package_sources}"
-		PACKAGES_PREP="${PACKAGES_PREP} ${package_prep}"
-		PACKAGES_COMPILE="${PACKAGES_COMPILE} ${package_archive}"
+		PACKAGES_COMPILE="${PACKAGES_COMPILE} ${package_make}_compile"
+		PACKAGES_ARCHIVE="${PACKAGES_ARCHIVE} ${packages_archive}"
 		PACKAGES_INSTALL="${PACKAGES_INSTALL} ${package_install}"
 	fi
 	PACKAGES_CLEAN="${PACKAGES_CLEAN} ${package_make}_clean"
@@ -156,10 +163,11 @@ done >> "${BUILDER_MAKEFILE}"
 
 cat<<EOF >> "${BUILDER_MAKEFILE}"
 packages_fetch: ${PACKAGES_SOURCES}
-packages_prep: ${PACKAGES_PREP}
-packages_clean: ${PACKAGES_CLEAN}
+packages_prep: ${PACKAGES_SOURCES}
 packages_compile: ${PACKAGES_COMPILE}
+packages_archive: ${PACKAGES_ARCHIVE}
 packages_install: ${PACKAGES_INSTALL}
+packages_clean: ${PACKAGES_CLEAN}
 EOF
 
 # vim: filetype=sh
