Build infrastructure change...
* Renamed build-info to build-query.  The build-query tool is now
  responsible for looking up pretty much any and all package
  information, and all of the tools should use it instead of making
  assumptions about paths.

* Redesigned the package structure to support <category>/<package>.
  When a request is made that excludes the <category> then the
  <project_name> is assumed to be the category.

* Currently anything in the buildtools/ category is not cleaned up
  during build-clean.  In the future there will be a NOCLEAN option as a
  category rule that the Buildrules file implicitly inherits.

diff --git a/scripts/builder/build-install b/scripts/builder/build-install
--- a/scripts/builder/build-install
+++ b/scripts/builder/build-install
@@ -1,12 +1,16 @@
 #!/usr/bin/env build
 
 echo "installing: ${1}"
-import "${1}"
+eval $(build query --environ "${1}")
 
-ARCHIVE_FORMAT="tar.bz2"
+# FIXME this should be taken care of by the build config
+if [ -z "${ARCHIVE_FORMAT}" ]; then
+	ARCHIVE_FORMAT="tar.bz2"
+fi
+
 [ -f "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" ] || die "archive does not exist for package '${NAME}'"
-if [ ! -d "${BUILDER_SYSROOT}" ]; then
-	mkdir -p "${BUILDER_SYSROOT}" || die "failed to create system root @ '${BUILDER_SYSROOT}'"
+if [ ! -d "${SYSROOT}" ]; then
+	mkdir -p "${SYSROOT}" || die "failed to create system root @ '${SYSROOT}'"
 fi
 
 # FIXME the builder configs should decide the binpkg archive format.
@@ -16,7 +20,7 @@ case "${ARCHIVE_FORMAT}" in
 (*)		die "unsupported archive format '${ARCHIVE_FORMAT}'";;
 esac
 
-cd "${BUILDER_SYSROOT}" && ${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" | tar x
-cp -a "${L}/.compiled" "${L}/.installed"
+cd "${SYSROOT}" && ${ARCHIVE_DECOMPRESSOR} "${BUILDER_ATFDIR}/${NAME}-${VERSION}.${ARCHIVE_FORMAT}" | tar x
+cp -a "${W}/.compiled" "${W}/.installed"
 
 # vim: filetype=sh
